services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  order:
    image: ${ORDER_IMAGE}
    expose:
      - "8080"
    volumes:
      - order-logs:/usr/local/tomcat/logs
  stevedore:
    image: ${STEVEDORE_IMAGE}
    expose:
      - "8080"
    volumes:
      - stevedore-logs:/usr/local/tomcat/logs
      
volumes:
  order-logs: {}
  stevedore-logs: {}
