services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /etc/devops/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  order:
    image: ${ORDER_IMAGE}
    expose:
      - "8080"
    volumes:
      - order-logs:/usr/local/tomcat/logs
      
volumes:
  order-logs: {}
