version: "3.9"
services:
    mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=stevedore
    ports:
      - 3307:3306

  
  app:
    image: testimage
    env_file: ./.env
    ports:
      - 3307:3306

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mariadb://3306/stevedore?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver",
            "spring.jpa.hibernate.ddl-auto" : "update"
            "spring.thymeleaf.cache" : "false"
            "spring.thymeleaf.suffix" : ".html"
          }'

    volumes:
      - user-example-logs:/usr/local/tomcat/logs


volumes:
  user-example-logs: {}
