services:
  web:
    image: stevedore_web
    restart: 'always'
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    image: mariadb
    restart: 'always'
    volumes: 
      - "/var/lib/mysql/data:stevedore_data"
      - "/var/lib/mysql/logs:stevedore_log"
      - /var/docker/mariadb/conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stevedore
      MYSQL_USER: root
      MYSQL_PASSWORD: root
