name: Test dispatch
on: 
  repository_dispatch:
      types: [deploy]

env:
  PERMITTED_REPOS: '["HARBOUR_IMAGE", "SHIPPING_IMAGE", "PORT_IMAGE", "STEVEDORE_IMAGE", "ORDER_IMAGE"]'
  IMAGE_OWNER: "default"
  IMAGE_TAG: "default"

jobs:
    build-and-deploy:
      name: Setup, Build and Publish
      runs-on: ubuntu-latest
      steps:
      
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: 'Update ENV vars'
        run: |
            echo "${{ github.event.client_payload.image_owner }}"
            echo "IMAGE_OWNER=${{ github.event.client_payload.image_owner }}" >> $GITHUB_ENV
            echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
     
      - name: "Check if payload is from the list of permitted repositories"
        if: ${{ !contains(env.PERMITTED_REPOS, env.IMAGE_OWNER) }}
        uses: actions/github-script@v5.0.0
        with:
            script: |
                core.setFailed('Image owner not permitted.')
        
      - name: Update secret variables
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: ${{ env.IMAGE_OWNER }}
          value: ${{ env.IMAGE_TAG }}
          token: ${{ secrets.PAT }}
      - name: Repository Update
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository:  com619-2021/IntegrationA 
          event-type: update
