name: Test-Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        working-directory: ./experimental/Testing/
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:2.3.0:dockerBuild
        
