name: Test-Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build with Maven
        working-directory: ./experimental/Testing/
        run: | 
          mvn compile com.google.cloud.tools:jib-maven-plugin:2.8.0:build \-Dimage=ghcr.io/${{ github.repository_owner }}/testimage:latest
        
      - name: "Upload Docker image to Azure"
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.AZURE_USERNAME }}'
          server: '${{ secrets.AZURE_HOSTNAME }}'
          ssh_private_key: '${{ secrets.AZURE_KEY }}'
          local_path: './experimental/Testing/docker/docker-compose.yml'
          remote_path: '/tmp/docker-compose.yml'
      
          
