name: Restarting Container Images on Azure
on: 
    repository_dispatch:
        types: [update]
        
jobs:
    deploy:
      name: Deploy the latest image
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      - name: Upload docker-compose to Azure
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.AZURE_USERNAME }}
          server: ${{ secrets.AZURE_HOSTNAME }}
          ssh_private_key: ${{ secrets.AZURE_KEY }}
          local_path: './docker/docker-compose.yml'
          remote_path: '/home/devops1/devel/gitrepos/IntegrationA/docker/docker-compose.yml'
          
      - name: Upload NGINX config to Azure
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.AZURE_USERNAME }}
          server: ${{ secrets.AZURE_HOSTNAME }}
          ssh_private_key: ${{ secrets.AZURE_KEY }}
          local_path: './nginx/app.conf'
          remote_path: '/home/devops1/devel/gitrepos/IntegrationA/docker/data/nginx/conf.d/app.conf'
      
      - name: Run docker-compose on Azure
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.AZURE_USERNAME }}
          host: ${{ secrets.AZURE_HOSTNAME }}
          key: ${{ secrets.AZURE_KEY }}
          port: 22
          script: |            
            docker stop $(docker ps -a -q)
            ORDER_IMAGE=${{ secrets.ORDER_IMAGE }} STEVEDORE_IMAGE=${{ secrets.STEVEDORE_IMAGE }} docker-compose -f /home/devops1/devel/gitrepos/IntegrationA/docker/docker-compose.yml up --remove-orphans -d
